# Generated by Django 4.2.7 on 2023-11-30 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='add_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
